# Transit Plugin Configuration
settings:
  maxTapDuration: 7200  # Maximum journey time in seconds
  currency: "$"
  defaultSystem: "Subway"
  saveInterval: 300     # Auto-save interval in seconds
  debug: false

database:
  type: YAML    # YAML or MYSQL
  mysql:
    host: localhost
    port: 3306
    database: transit
    username: user
    password: pass
    prefix: transit_

systems:
  Subway:
    name: "Metro Subway"
    fareType: ZONE
    maxFare: 8.00
    zones:
      rings:
        "1": 0
        "2": 1
        "3": 2
      groups:
        city_center: ["1A", "1B"]
        suburbs: ["2A", "2B"]
      rules:
        same_zone:
          from: "\\d+"
          to: "\\1"
          fare: 2.50
        adjacent:
          ringDifference: 1
          fare: 3.00
        default: 5.00

  Bus:
    name: "City Bus"
    fareType: FLAT
    fare: 2.75
    maxFare: 2.75

  Rail:
    name: "Light Rail"
    fareType: DISTANCE
    baseRate: 2.00
    perBlock: 0.01
    maxFare: 5.00

staff:
  minimumBalance: 5000.0
  paymentNotifications: true
  defaultPeriod: MONTHLY

gates:
  enableAnimations: true
  soundEffects: true
  particleEffects: true